---
# tasks file for mongo-db

  - name: Copy file with owner and permissions
    copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/
      owner: root
      group: root
      mode: 0644

  - name: Install mongodb-org package
    yum:
     name: mongodb-org
     state: present

  - name: Start the service
    service:
      name: mongod
      state: started
